FROM python:3.13.7-alpine

RUN apk add --no-cache ca-certificates docker-cli docker-cli-compose

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY server.py /app/server.py

EXPOSE 4000

CMD ["gunicorn", "server:app", "--bind", "0.0.0.0:4000", "--workers", "2"]