FROM python:3.13.7-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates git curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY updater.py /app/updater.py

EXPOSE 4000

CMD ["python", "updater.py"]