FROM python:3.13.7-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY server.py /app/server.py

EXPOSE 4000

CMD ["gunicorn", "server:app", "--bind", "0.0.0.0:4000", "--workers", "2"]